#spring.datasource.url = jdbc:postgresql://localhost:5432/hodophiliadb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto= update
#
## App Properties
#hodophilia.app.jwtSecret=hodophiliaSecretKey
#hodophilia.app.jwtExpirationMs=86400000


spring:
 datasource:
         url: "jdbc:postgresql://localhost/hodophiliadb"
         driverClassName: org.postgresql.Driver
         username: postgres
         password: postgres
 jpa:      
           database: POSTGRESQL
           show-sql: false
           hibernate.ddl-auto: update
           properties:
             hibernate:
               jdbc:
                 lob:
                   non_contextual_creation: true
               dialect: org.hibernate.dialect.PostgreSQLDialect
 security:
    oauth2:
      client:
        registration:
         google:
          clientId: 253434983541-pcoqhs7d8l05r176fod88imfljmsrlhk.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile
  
hodophilia:
   app:
      jwtSecret: hodophiliaSecretKey
      jwtExpirationMs: 86400000