spring:
 datasource:
         url: "jdbc:postgresql://localhost/hodophiliadb"
         driverClassName: org.postgresql.Driver
         username: postgres
         password: IdRatherUseMariaDB
 jpa:      
           database: POSTGRESQL
           show-sql: false
           hibernate.ddl-auto: update
           properties:
             hibernate:
               jdbc:
                 lob:
                   non_contextual_creation: true
               dialect: org.hibernate.dialect.PostgreSQLDialect
               
 
 security:
    oauth2:
      client:
        registration:
          google:
            client-id: 253434983541-pcoqhs7d8l05r176fod88imfljmsrlhk.apps.googleusercontent.com
            client-secret: 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
            #redirectUri: "http://localhost:3000/login"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
                - email
                - profile
  
hodophilia:
   app:
      jwtSecret: hodophiliaSecretKey
      jwtExpirationMs: 86400000
   
   oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/login
 

 
      